In [1]:
import numpy as np
import json

In [2]:
with open("3Simplex.json", "r") as file:
    data = json.load(file)

In [3]:
polygons = data["Polygons"]

In [4]:
vertices = [np.array(x) for x in set(tuple(v) for p in polygons for v in p)]

In [5]:
vertices

[array([-0.66666667,  1.88561808,  0.        ]),
 array([-0.66666667, -0.94280904,  1.88561808]),
 array([2., 0., 0.]),
 array([-0.66666667, -0.94280904, -1.88561808])]

In [6]:
v1, v2, v3, v4 = vertices

In [7]:
v0 = (v3 + v4) * 0.5

In [8]:
angle = np.arccos(np.dot((v1 - v0), (v2 - v0)) / (np.linalg.norm(v1 - v0) * np.linalg.norm(v2 - v0)))

In [9]:
angle * 180 / np.pi

68.43187056435211